### ISSUE TITLE
How to turn on proper bucket support?

### ISSUE THREAD

**Issue by IFantastic** [HadoopIt/rnn-nlu#3]
Hi, thank you for the code.
How to turn on properly a support for buckets of different size?
This model works properly only with 1 bucket size right now.

**Comment by HadoopIt** [comment]
You may refer to the TensorFlow sequence-to-sequence model example for further details on bucketing and padding. Basically, you can define a number of buckets of various size according to the sequence length in your corpus, and put each data sample to the corresponding bucket. More details can be found at:
https://www.tensorflow.org/tutorials/seq2seq/#bucketing_and_padding
