### ISSUE TITLE
Linear is expecting 2D arguments: [[2, None, 128]] with num_layers=2

### ISSUE THREAD

**Issue by D-X-Y** [HadoopIt/rnn-nlu#4]
Hi, I got this error in https://github.com/HadoopIt/rnn-nlu/blob/master/seq_classification.py#L71

I config the num_layers=2 for MultiRNN, this error occurs.

When I use "num_layers=1" or "num_layers=2 and state_is_tuple=False", the code is fine.

I think there needs some modification for encoder_state, but I'm not quite familiar with rnn in tensorflow.

Would you mind fix this bug?

Thanks a lot

**Comment by HadoopIt** [comment]
Sorry for the delayed updates. The code is now updated to work with the latest TensorFlow API r1.2
