### ISSUE TITLE
some error in the function _step of seq_labeling.py 

### ISSUE THREAD

**Issue by elias-1** [HadoopIt/rnn-nlu#5]
Refer to [code](https://github.com/HadoopIt/rnn-nlu/blob/master/seq_labeling.py#L44) .

The logit set shape from itself. The code may be writed as this 
logit.set_shape(zero_logit.get_shape())

May some help.

**Comment by HadoopIt** [comment]
Thank @elias-1 for this suggestion. Fix has been added from your pull request.
