### ISSUE TITLE
Update with the recent changes in Tensorflow

### ISSUE THREAD

**Issue by zuxfoucault** [HadoopIt/rnn-nlu#7]
Due to this [change](https://github.com/tensorflow/tensorflow/commit/e8482ab23bd0fce5c2941f6a190158bca2610a35) in Tensorflow as the suggestion:
> writing:  `MultiRNNCell([lstm] * 5)` will now build a 5-layer LSTM stack where each
>  layer shares the **same** parameters.  To get 5 layers each with their own
>  parameters, write: `MultiRNNCell([LSTMCell(...) for _ in range(5)])`.

Should `cell = tf.contrib.rnn.MultiRNNCell([single_cell] * num_layers])` in [line](https://github.com/HadoopIt/rnn-nlu/blob/master/multi_task_model.py#L51) be updated to `cell = tf.contrib.rnn.MultiRNNCell([single_cell for _ in range(num_layers)])`?
Thanks!

**Comment by zuxfoucault** [comment]
Besides, since `from tensorflow.python.ops import rnn` in [line](https://github.com/HadoopIt/rnn-nlu/blob/master/generate_encoder_output.py#L18) has moved to `from tensorflow.contrib import rnn`.

I'm not sure which rnn.rnn() in [line](https://github.com/HadoopIt/rnn-nlu/blob/master/generate_encoder_output.py#L55) should be corresponded to in the newer Tensorflow version. Thanks!

**Comment by raphael-sch** [comment]
You need to instantiate the cell multiple times. Something like this:

    # Create the internal multi-layer cell for our 
    cell_type = tf.nn.rnn_cell.GRUCell
    if use_lstm:
        cell_type = tf.nn.rnn_cell.BasicLSTMCell
    cell = cell_type(size)
    if num_layers > 1:
        cell = tf.nn.rnn_cell.MultiRNNCell([cell_type(size) for _ in range(num_layers)])`

**Comment by HadoopIt** [comment]
Thanks @raphael-sch and @zuxfoucault, the code is now updated to work with the latest TensorFlow API r1.2. Sorry for the delayed updates.
